# Generated by Django 4.2.1 on 2023-05-05 01:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_cree_tabla_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.TextField()),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto')),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
